services:
  # Web service for the Chainlit application
  - type: web
    name: aihackathon-app
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: chainlit run app/app.py --port $PORT --host 0.0.0.0
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: LOG_LEVEL
        value: INFO
      - key: DATABASE_URL
        fromDatabase:
          name: aihackathon-db
          property: connectionString
      - key: CHAINLIT_AUTH_SECRET
        generateValue: true
    healthCheckPath: /api/v1/health

# Database service
databases:
  - name: aihackathon-db
    plan: free
    postgresMajorVersion: 15
    ipAllowList:
      - source: 0.0.0.0/0
        description: Allow all connections (not recommended for production)
    databaseName: aihackathon
    user: postgres
